AWSTemplateFormatVersion: '2010-09-09'
Uid: "1000"
Gid: "1000"
RootDirectory:
CreationInfo:
OwnerUid: "1000"
OwnerGid: "1000"
Permissions: "0755"
Path: "/models"


LibreTranslateMountTarget:
Type: AWS::EFS::MountTarget
Condition: UseEFS
Properties:
FileSystemId: !Ref LibreTranslateEFS
SubnetId: !Select [ 0, !Ref SubnetIds ]
SecurityGroups: !Ref SecurityGroupIds


LibreTranslateFunction:
Type: AWS::Lambda::Function
Properties:
FunctionName: !Sub "${AWS::StackName}-libretranslate"
PackageType: Image
Role: !GetAtt LambdaExecutionRole.Arn
Timeout: !Ref LambdaTimeout
MemorySize: !Ref LambdaMemory
Code:
ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:${ImageTag}"
Environment:
Variables:
LT_S3_BUCKET: !If [ CreateBucket, !Ref ModelBucket, !Ref ModelBucketName ]
LT_S3_MODEL_KEY: !Ref ModelObjectKey
LT_EFS_MOUNT: "/mnt/models"
VpcConfig: !If
- UseEFS
- SubnetIds: !Ref SubnetIds
SecurityGroupIds: !Ref SecurityGroupIds
- !Ref "AWS::NoValue"
FileSystemConfigs: !If
- UseEFS
- - Arn: !GetAtt LibreTranslateEFSAccessPoint.Arn
LocalMountPath: "/mnt/models"
- !Ref "AWS::NoValue"


Outputs:
LambdaFunctionName:
Description: Name of the Lambda function
Value: !Ref LibreTranslateFunction
LambdaFunctionArn:
Description: ARN of the Lambda function
Value: !GetAtt LibreTranslateFunction.Arn
ModelBucketUsed:
Description: S3 bucket where models should be uploaded
Value: !If [ CreateBucket, !Ref ModelBucket, !Ref ModelBucketName ]